#293 Feat : add address numbering, button to NavLink
sdp-tech/SASM_FE pull request #389
Opened 2023-03-16 13:15 UTC by youngsikkk

**목적**
1. sdp-tech#293 Feat.add address numbering : SEO 개선을 위해 각각 url 달아주기 ( 모든 장소 및 스토리 url로 접근 가능하도록 하도록 )

2. sdp-tech#293 button to NavLink : SEO 개선을 위해 button -> NavLink 로 변경

**변경 파일 3가지**
1. src/_App.jsx_

2. src/components/SpotMap/SpotList/_ItemCard.js_

3. src/components/common/_Pagination.jsx_

**변경 파일 변경점**
1. App.jsx 에 <Route path="/map/:id" element={<SpotMap />} /> 추가

2. ItemCard.js 에 TitleBox와 ImgBox 를 각각 StyledBox 와 StyledLink 로 변경,
그 후 StyledLink to={`/map/${placeData.id}`} 를 추가해주어 모달창에 각각의 url 배정

3. Pagination.jsx 에 styled.button`을 styled(NavLink)로 변경

**추가사항**
- package.json 및 package-lock.json 삭제
- git push 하는 과정에서 오류가 발생하여 ItemCard.js 의 경우 하드업로드(직접 업로드)를 통하여 했음.
그 과정에서 로그가 복잡해짐

2023-03-16 14:47 UTC, sejongk requested changes
package-lock.json 및 package.json 파일을 삭제하지 않고, commit에서만(이 Pull request에서만) 제외해주시면 될 것 같습니다

2023-03-17 06:11 UTC, dgfh0450 reviewed
추후에 수정 필요

2023-03-17 06:11 UTC, dgfh0450 commented on src/components/SpotMap/SpotList/ItemCard.js
> +          <StyledBox to={`/map/${placeData.id}`}>
Link가 placeData.place_name에만 적용되기
이렇게 적용할 경우, LikeButton이 작동되지 않을 가능성이 있음.

2023-03-17 06:11 UTC, dgfh0450 commented on src/components/SpotMap/SpotList/ItemCard.js
> +  flex-flow: row wrap;
후에 코드 간소화 필요

2023-03-17 06:11 UTC, dgfh0450 commented on src/components/SpotMap/SpotList/ItemCard.js
> +const StyledLink = styled(NavLink)`
https://velog.io/@seong-dodo/React-Link%EC%99%80-NavLink
isActive옵션이 없으면 NavLink일 필요는 없음.

2023-03-17 06:52 UTC, closed without merging